apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-config
  namespace: andorra
data:
  REGION: "andorra"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_URL: "redis://redis:6379"
  MONGO_URI: "mongodb+srv://<user>:<pass>@cluster.mongodb.net/traffic?retryWrites=true"
  JWT_SECRET: "changeme-replace-in-production"
  JWT_ALGORITHM: "HS256"
  JOURNEY_MANAGEMENT_URL: "http://journey-management:8000"
  ANDORRA_ROUTE_URL: "http://route-service:8000"
  LAOS_ROUTE_URL: "http://data-gateway-laos:8000"
  CAMBODIA_ROUTE_URL: "http://data-gateway-cambodia:8000"
